### ISSUE TITLE
Bones on the opposite side of character mesh are flipped

### ISSUE THREAD

**Issue by Gnates** [Befzz/blender3d_import_psk_psa#1]
I'm using Blender 2.78c. Your addon works well with the exception of some bones being flipped on import: https://i.imgur.com/gXjEVUV.png (bones on the left side of image)

What I usually do is append a .L or .R to the end of the bone names and then make adjustments to the correctly oriented bones (I don't like disconnected bones, so I connect them to each other) which will mirror to the opposite bones. 

There is another Blender addon developer who is working on something similar but might need some more work: https://github.com/RhyCynn/cynn_import_psa_psk/

Anyway, thank you for making this. Please continue to improve this addon.

**Comment by Befzz** [comment]
@Gnates hello!

It's a pretty old plugin and my edition of it is far from ideal.  

I know about "bone orientation problem".
But have no real knowledge how blender's bones works. FeelsBadMan
I may try to fix it.

Can you provide any psk/psa files?
That imports good and bad.
(using google drive or similar)

Thank you.

**Comment by Gnates** [comment]
Here is 1 psk model from an Unreal Engine 3 game, DC Universe Online. https://my.mixtape.moe/yareec.zip

**Comment by Gnates** [comment]
The NoAnim branch looks great, so far. 
I prefer to make custom animations in Blender, so this was a great idea. Thank you.
Is it possible to have an import option that allows you to connect the bones? Mostly just the limb bones, but I guess it would be insane considering the various different rigging/bone-naming standards.

**Comment by Befzz** [comment]
> to connect the bones

You mean *Connected* checkbox in bone **Relations** properties, or just want them to be looks connected (extended length)

btw, i did last variant: 😄 

![psk_boneautosize](https://user-images.githubusercontent.com/1160036/28476343-6d775926-6e58-11e7-8a5b-59d1c931ec4e.jpg)

![psk_bonehide](https://user-images.githubusercontent.com/1160036/28476354-7641edaa-6e58-11e7-961a-4b534986334f.jpg)

**Comment by Gnates** [comment]
I just installed the latest NoAnim version, and the Auto-size bones option is now available. This might be perfect.
Also, the previous connected bones idea (similar to the bone relations properties) was me thinking it would make Inverse Kinematics/ IK-controls operate better with connected bones, but I guess the benefit of disconnected bones with IK-controls can create a cartoon-like stretch to hands and feet.
I think the Auto-size bones option should be fine for now. Thanks Befzz.

**Comment by nigelmerle** [comment]
Use unwrap 3d, all your problems are solved ! 

I have a good news for all of you out there who want to import psk/psa, no more 3ds max needed !!!!, no more actorx which produces huge file on export,
I just bought a software called unwrap 3d (it can optimize your files and you get small file size on export), today they have a huge update in their psk/psa plugin, they have added an option to import our psk with textures on !, the plugin has to be downloaded on their webpage, i am so happy i had to share it with you guys: https://www.unwrap3d.com/u3d/downloads.aspx     , under third party plugin you can download it under the name: unreal tournament psk/psa  ...this is huge !, if you do not understand how the software works you can contact support, i was having issues lately to understand how the software works and they help me solve it under 24 hours...unwrap 3d: a very simple  solution to all your problems and a very powerful tool in good hands ...there is support for fbx,.x, dae,psk/psa,3ds, autocad,mimiku,cinema4d, milkshape...and the list goes on, they also offer support to import some popular games..spread the word !, disappointed with blender , 3ds max exporters., having sleepless night searching the internet for converting direct .x or any 3d file format..etc...where all popular software fails unwrap 3d suceed ! just try and let me know !!!, it is a good tool for working with gameguru as well! .cheers
