### ISSUE TITLE
Blender 2.8 Alpha (importer broken)

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#12]
Hey Befzz, just letting you know that latest version of Blender 2.8 alpha requires the importer to be updated again, easy fix though just need to change the blender version number to ( 2, 80, 0 ) to make it work, figured this one out myself surprisingly lol (read the error message in info, was related to addons_utils script line 359, there was the version number etc)

**Comment by remizik** [comment]
@ArchUser87 Hi, where do you make that change exactly ?

**Comment by remizik** [comment]
trying this addon on Blender 2.79b works for most PSK files, but I still have some with problems : 
![image](https://user-images.githubusercontent.com/24875086/42372435-7fcc555e-8112-11e8-8f1e-ead138004524.png)

opening the PSK file with another software (SkelEdit) shows no issue : 
![image](https://user-images.githubusercontent.com/24875086/42372544-c54286f8-8112-11e8-87ef-e611e1d13523.png)

**Comment by ArchUser87** [comment]
@remizik You change it in the wrong script, you want to do it for the importer itself not the addon_utils like you have done, this is most likely why meshes are broken..

![tempsnip13](https://user-images.githubusercontent.com/25260650/42372924-dd93f482-8156-11e8-9486-3e8dfc06713c.PNG)

**Comment by remizik** [comment]
I don't have the same structure as you apparently !

![image](https://user-images.githubusercontent.com/24875086/42373266-b0dcc924-8114-11e8-8cbd-4af010eabdc9.png)

**Comment by ArchUser87** [comment]
it looks like you have downloaded the page the script was on?

**Comment by remizik** [comment]
Ok I did the change and now I have the PSK/PSA import options : 
![image](https://user-images.githubusercontent.com/24875086/42373516-65850b16-8115-11e8-988d-fd08a8567c71.png)

But still nothing in the 3D view after importing my PSK file (I tried zooming out or in to the max, there's nothing)

**Comment by ArchUser87** [comment]
(Will also be under the Tool Panel (press T to bring up)

Do you have a link of the model you trying to import, will test to see if works for me.

Also this for Blender 2.79 or Blender 2.80 or both?

**Comment by remizik** [comment]
I added the file in my post :)

2.79b opens the file but with the mesh issue (see my screenshot above)
2.80 gets me an empty 3D space

**Comment by remizik** [comment]
Don't know if it's relevant, but I also get this when I press "import PSK path" and add my folder where all my PSK files are : 
![image](https://user-images.githubusercontent.com/24875086/42373868-76174dda-8116-11e8-8759-ea7bd9c3e5e3.png)

but I might be doing it wrong, I actually have basically no idea what i'm doing :D I'm a total noob, I just want to create STL files from PSK files in the end :)

**Comment by remizik** [comment]
I just closed blender and restored the addon_utils for the downloaded blender zip, and tried again.

Still nothing in the 3D view, and I get this message : 

![image](https://user-images.githubusercontent.com/24875086/42374494-998df078-8118-11e8-842b-cee057d87abd.png)

**Comment by ArchUser87** [comment]
click File and load factory settings and try again, if still doesn't work, remove all traces of 2.80 and start again....

**Comment by remizik** [comment]
I'll try that :)  
Do I need to untick anything from here before importing ?
![image](https://user-images.githubusercontent.com/24875086/42374612-efbe401a-8118-11e8-9cb8-1da7b9fc8444.png)

**Comment by remizik** [comment]
I redid everything from scratch : 
- cleaning %appdata%
- deleting my Blender folder
- extracting the ZIP downloaded from the Blender website
- opening Blender
- go into preferences
- install addon from file
- select the "io_import_scene_unreal_psa_psk_280.py" downloaded from here
- clic "save user settings"
- close Blender
- edit the file "C:\TOOLS\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk.py"
- change the version number to "_"blender": (2, 80, 0),_"
- open Blender again
- try importing the PSK file I shared with you
- same behavior :(

**Comment by ArchUser87** [comment]
No just leave it default for most cases, however your psk looks different to mine, so I think the issue you are having is you have the wrong psk importer enable....

Mine....(2.80)
![psk1](https://user-images.githubusercontent.com/25260650/42375482-08de5a80-815f-11e8-8fae-375d9fa88f42.PNG)
![psk2](https://user-images.githubusercontent.com/25260650/42375483-09115c64-815f-11e8-888b-835e74d9d0aa.PNG)

**Comment by ArchUser87** [comment]
You have the the one that comes with Blender enable, not Befzz's one, this is the issue, you want to click on Install Add-on from file down below, find and select befzz one you downloaded and enable that one, then click on Save User Settings for it to be enable each time you load Blender....

**Comment by remizik** [comment]
I'm at the airport right now so I can't test much. I'm pretty sure I did what you said but help through discord would be much appreciated :) send me the link and I'll come by asap. Cheers

**Comment by ArchUser87** [comment]
all good Blenux#9405

**Comment by Befzz** [comment]
@remizik you need to install and enable right addon:  

Install:  
![install addon](https://user-images.githubusercontent.com/1160036/42383637-7243754c-8140-11e8-8659-ab53c69de331.PNG)

Enable:  
![rightaddon](https://user-images.githubusercontent.com/1160036/42383469-f7b89e60-813f-11e8-9f49-8dea82c1ad3d.PNG)

You don't need to edit anything, after that.

**Comment by remizik** [comment]
Ok so the thing is, I'm a total noob with GitHub too, so when I tried to get the file I right clicked on it and did "save as" which gave me this content : 

![image](https://user-images.githubusercontent.com/24875086/42388382-a84dd9e8-8145-11e8-9baa-425700ec5a2f.png)

Copying the code manually and then put it in a txt editor and saving it as a .py file worked much better.
Sorry about all this, I'm ashamed 👎

**Comment by Befzz** [comment]
if you need only 1 file from github, get raw version
![raw](https://user-images.githubusercontent.com/1160036/42388996-fe0485a8-814f-11e8-929c-3700cf2d401b.PNG)

**Comment by remizik** [comment]
TIL !
thanks for the explanation and for that awesome script, and sorry about all that spam just because I don't know how to use github :/

**Comment by CastelHQ** [comment]
Latest issue:
`-----------------------------------------------
---------EXECUTING PSK PYTHON IMPORTER---------
-----------------------------------------------
 Importing file: D:\uModel\UmodelExport\MKX\CHAR_LiuKang_E\Meshes\LiuKang_E.psk
Traceback (most recent call last):
  File "C:\Users\Castel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1680, in execute
    error_callback = util_ui_show_msg
  File "C:\Users\Castel\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 707, in pskimport
    psk_bone.mat_world.translation = parent.mat_world.translation + parent.mat_world_rot * psk_bone.orig_loc
TypeError: Element-wise multiplication: not supported between 'Matrix' and 'Vector' types

location: <unknown location>:-1

location: <unknown location>:-1
`
