### ISSUE TITLE
Animation Sync with Blender Timeline

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#13]
Hi Befzz, just wondering if there is any possibility that you could look into adding a feature where when loading a animation into a model, it syncs the Blender Time-line to the length of that animation, so say one animation has 50 frames, so when playing it the blender time-line only has 50 frames in the time-line, basically what the ActorX Importer "Update Animation Length" does...

Thanks and no problem if can't.

**Comment by ArchUser87** [comment]
Actually Blender already has the feature, might make it easier for you to implement into the importer?

![timeline](https://user-images.githubusercontent.com/25260650/43336504-798509c6-9214-11e8-8d64-29545294da29.png)

**Comment by Blenux** [comment]
Awesome very nice, works great, does have a extra frame at end of the animation thats gets imported but other then that works exactly like the ActorX Importer does! Thanks heaps...

**Comment by michaelpayne02** [comment]
@Blenux It does trim the non-looping animations. I just had multiple emotes appended to my uModel session and when they were exported, the longest one was 250 frames (a.k.a. blender's default frame range)

@Befzz Everything looks good. You can close this one
