### ISSUE TITLE
Can't import anything at Blender 2.80.21

### ISSUE THREAD

**Issue by Florst** [Befzz/blender3d_import_psk_psa#16]
![error](https://user-images.githubusercontent.com/42754029/44688034-55859900-aa29-11e8-8acb-96fc159311e3.png)

**Comment by Befzz** [comment]
fixed at *latest* branch  

https://github.com/Befzz/blender3d_import_psk_psa/issues/15#issuecomment-414803522

**Comment by Blenux** [comment]
Broken once again sadly, new error is related to 

> bpy.types.INFO_MT_file_import.append(menu_import_draw)

changes mention here I believe.

https://developer.blender.org/T52599

Tried to fix but then other errors came up lol.

**Comment by Blenux** [comment]
Rechecked the log window, has abit more info :O

> Warning: class IMPORT_SCENE_OT_psk contains a properties which should be a field!
> C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1833
>     make field: IMPORT_SCENE_OT_psk.fBonesize
>     make field: IMPORT_SCENE_OT_psk.fBonesizeRatio
>     make field: IMPORT_SCENE_OT_psk.bSpltiUVdata
>     make field: IMPORT_SCENE_OT_psk.bReorientBones
>     make field: IMPORT_SCENE_OT_psk.bReorientDirectly
>     make field: IMPORT_SCENE_OT_psk.import_mode
>     make field: IMPORT_SCENE_OT_psk.bDontInvertRoot
>     make field: IMPORT_SCENE_OT_psk.bFilenameAsPrefix
>     make field: IMPORT_SCENE_OT_psk.bActionsToTrack
>     make field: IMPORT_SCENE_OT_psk.bUpdateTimelineRange
> Warning: class IMPORT_SCENE_OT_psk contains a properties which should be a field!
> C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1833
>     make field: IMPORT_SCENE_OT_psk.filepath
>     make field: IMPORT_SCENE_OT_psk.filter_glob
> Warning: class IMPORT_SCENE_OT_psa contains a properties which should be a field!
> C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1833
>     make field: IMPORT_SCENE_OT_psa.fBonesize
>     make field: IMPORT_SCENE_OT_psa.fBonesizeRatio
>     make field: IMPORT_SCENE_OT_psa.bSpltiUVdata
>     make field: IMPORT_SCENE_OT_psa.bReorientBones
>     make field: IMPORT_SCENE_OT_psa.bReorientDirectly
>     make field: IMPORT_SCENE_OT_psa.import_mode
>     make field: IMPORT_SCENE_OT_psa.bDontInvertRoot
>     make field: IMPORT_SCENE_OT_psa.bFilenameAsPrefix
>     make field: IMPORT_SCENE_OT_psa.bActionsToTrack
>     make field: IMPORT_SCENE_OT_psa.bUpdateTimelineRange
> Warning: class IMPORT_SCENE_OT_psa contains a properties which should be a field!
> C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1833
>     make field: IMPORT_SCENE_OT_psa.filepath
>     make field: IMPORT_SCENE_OT_psa.filter_glob
> Warning: class PskImportOptions contains a properties which should be a field!
> C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1833
>     make field: PskImportOptions.fBonesize
>     make field: PskImportOptions.fBonesizeRatio
>     make field: PskImportOptions.bSpltiUVdata
>     make field: PskImportOptions.bReorientBones
>     make field: PskImportOptions.bReorientDirectly
>     make field: PskImportOptions.import_mode
>     make field: PskImportOptions.bDontInvertRoot
>     make field: PskImportOptions.bFilenameAsPrefix
>     make field: PskImportOptions.bActionsToTrack
>     make field: PskImportOptions.bUpdateTimelineRange
> Warning: class PSKPSA_OT_message contains a properties which should be a field!
> C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1833
>     make field: PSKPSA_OT_message.message
> Exception in module register(): C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py
> Traceback (most recent call last):
>   File "C:\Users\Blenux\Desktop\blender-2.80.0-git.053669e4aec-windows64\2.80\scripts\modules\addon_utils.py", line 399, in enable
>     mod.register()
>   File "C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1835, in register
>     bpy.types.INFO_MT_file_import.append(menu_import_draw)
> AttributeError: 'RNA_Types' object has no attribute 'INFO_MT_file_import'

**Comment by Befzz** [comment]
fix implemented in the **latest** branch: 
 https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

Known:  
"All actions to NLA track" is not working properly(use Dope Sheet -> Action Editor) (2.8 blender issue)

**Comment by Blenux** [comment]
Thanks, multi import is fun.
