### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by Zelorous** [Befzz/blender3d_import_psk_psa#17]
So, there are two things:
A.) The addon doesn't seem to support importing just the skeletons, even though it is an option.
B.) The addon allows multiple objects to be selected when trying to import, but only imports one object out of the selected objects. 

Thank you for tweaking the addon thus far, any help would be greatly appreciated.

**Comment by Befzz** [comment]
hey ;) Thanks for attention.  

A.) More details please. This works for me.  
  
![only_skel](https://user-images.githubusercontent.com/1160036/45312936-21849a80-b536-11e8-94d6-81be15797e20.png)

B.) Do you mean "multiple files" selected?  
Currently add-on importing only 1 file at a time.  

But you can select many.  

Yep. This misleading.  😸

**Comment by Zelorous** [comment]
Alright, as of right now I am importing Transformers FOC models. When I try to do the skeleton only, it doesnt work, after I hit import, nothing is imported. It does allow me to import only the mesh however. As for the other, I can select many objects to import, but it only will import one at a time.

**Comment by Befzz** [comment]
psk file does not always have a skeleton. It is OK.  
It can be in another .psk file.  (TERA, for example, have a psk files with skeletons only)

Importing one at a time is the intended usage.   
However, it is possible to make it more intuitive (many selected -> many imported).  
No one requested this future btw 😄 .  
<hr/>
Added notification(error) for this kind of situations:   

"Only skeleton import" + "actually no skeleton data in the file".

**Comment by Blenux** [comment]
I always thought the single importing of a mesh was a Blender limitation lol.

**Comment by Zelorous** [comment]
That feature would be nice

**Comment by Blenux** [comment]
Any updates Befzz?, sorry if your busy atm, I have 2 features that would be cool to add if possible.

**Comment by Befzz** [comment]
multiple-psk import added:
https://github.com/Befzz/blender3d_import_psk_psa/issues/16#issuecomment-432824638
