### ISSUE TITLE
Blender 2.80.30 - c94f806dc73

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#20]
New build seems to have broken the addon again,
 
**This is when adding it via User Preferences:**
addon_utils.disable: io_import_scene_unreal_psa_psk_280 not disabled
Modules Installed (io_import_scene_unreal_psa_psk_280) from 'C:\\Users\\Blenux\\Desktop\\io_import_scene_unreal_psa_psk_280.py' into 'C:\\Users\\Blenux\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'

**This is clicking the checkbox after adding it:**
Warning: class IMPORT_SCENE_OT_psk contains a properties which should be an annotation!
C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1796
    make annotation: IMPORT_SCENE_OT_psk.fBonesize
    make annotation: IMPORT_SCENE_OT_psk.fBonesizeRatio
    make annotation: IMPORT_SCENE_OT_psk.bSpltiUVdata
    make annotation: IMPORT_SCENE_OT_psk.bReorientBones
    make annotation: IMPORT_SCENE_OT_psk.bReorientDirectly
    make annotation: IMPORT_SCENE_OT_psk.import_mode
    make annotation: IMPORT_SCENE_OT_psk.bDontInvertRoot
    make annotation: IMPORT_SCENE_OT_psk.bFilenameAsPrefix
    make annotation: IMPORT_SCENE_OT_psk.bActionsToTrack
    make annotation: IMPORT_SCENE_OT_psk.bUpdateTimelineRange
Warning: class IMPORT_SCENE_OT_psk contains a properties which should be an annotation!
C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1796
    make annotation: IMPORT_SCENE_OT_psk.filepath
    make annotation: IMPORT_SCENE_OT_psk.filter_glob
Warning: class IMPORT_SCENE_OT_psa contains a properties which should be an annotation!
C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1796
    make annotation: IMPORT_SCENE_OT_psa.fBonesize
    make annotation: IMPORT_SCENE_OT_psa.fBonesizeRatio
    make annotation: IMPORT_SCENE_OT_psa.bSpltiUVdata
    make annotation: IMPORT_SCENE_OT_psa.bReorientBones
    make annotation: IMPORT_SCENE_OT_psa.bReorientDirectly
    make annotation: IMPORT_SCENE_OT_psa.import_mode
    make annotation: IMPORT_SCENE_OT_psa.bDontInvertRoot
    make annotation: IMPORT_SCENE_OT_psa.bFilenameAsPrefix
    make annotation: IMPORT_SCENE_OT_psa.bActionsToTrack
    make annotation: IMPORT_SCENE_OT_psa.bUpdateTimelineRange
Warning: class IMPORT_SCENE_OT_psa contains a properties which should be an annotation!
C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1796
    make annotation: IMPORT_SCENE_OT_psa.filepath
    make annotation: IMPORT_SCENE_OT_psa.filter_glob
Warning: class PskImportOptions contains a properties which should be an annotation!
C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1796
    make annotation: PskImportOptions.fBonesize
    make annotation: PskImportOptions.fBonesizeRatio
    make annotation: PskImportOptions.bSpltiUVdata
    make annotation: PskImportOptions.bReorientBones
    make annotation: PskImportOptions.bReorientDirectly
    make annotation: PskImportOptions.import_mode
    make annotation: PskImportOptions.bDontInvertRoot
    make annotation: PskImportOptions.bFilenameAsPrefix
    make annotation: PskImportOptions.bActionsToTrack
    make annotation: PskImportOptions.bUpdateTimelineRange
Warning: class PSKPSA_OT_message contains a properties which should be an annotation!
C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py:1796
    make annotation: PSKPSA_OT_message.message
Exception in module register(): C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py
Traceback (most recent call last):
  File "C:\Users\Blenux\Desktop\Blender 2.8\blender-2.80.0-git.c94f806dc73-windows64\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1798, in register
    bpy.types.INFO_MT_file_import.append(menu_import_draw)
AttributeError: 'RNA_Types' object has no attribute 'INFO_MT_file_import'

Traceback (most recent call last):
  File "C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1755, in draw
    props = context.scene.pskpsa_import
AttributeError: 'Scene' object has no attribute 'pskpsa_import'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\Blenux\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1755, in draw
    props = context.scene.pskpsa_import
AttributeError: 'Scene' object has no attribute 'pskpsa_import'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by Befzz** [comment]
It is strange, but `AttributeError: 'RNA_Types' object has no attribute 'INFO_MT_file_import'` was fixed already.  
However, i have found other errors, related to `label( text = "" )`.    
  
`make annotation:` can't find a nice way to fix this without splitting this file(2.80 vs. 2.79)

**Comment by Blenux** [comment]
Thanks mate, appreciate the updates.

**Comment by Gnates** [comment]
@Befzz Blender 2.80 Beta is now live,  and the Python API is ready.
https://www.blender.org/
Bug Reports are now open to the public.

**Comment by Blenux** [comment]
Beffz, would it be possible to put the import add onto the Sidebar now, seems to be where most of the addons are going to now (T for tools only).

Thanks again.

https://i.imgur.com/RnDmZvdl.png
