### ISSUE TITLE
Backwards Compatible with Blender 2.79

### ISSUE THREAD

**Issue by Gnates** [Befzz/blender3d_import_psk_psa#23]
Hey, happy new year.
At the time of this post, the add-on has 2 Branches:
- **master** ( https://github.com/Befzz/blender3d_import_psk_psa )
- **latest** ( https://github.com/Befzz/blender3d_import_psk_psa/tree/latest )

**Branch master:** https://github.com/Befzz/blender3d_import_psk_psa/blob/master/addons/io_import_scene_unreal_psa_psk_280.py
"name": "Import Unreal Skeleton Mesh (.psk)/Animation Set (.psa) (280)",
"author": "Darknet, flufy3d, camg188, befzz",
"version": (2, 7, 4),
"blender": (2, 80, 0),

**Branch latest:** https://github.com/Befzz/blender3d_import_psk_psa/blob/latest/addons/io_import_scene_unreal_psa_psk_280.py
"name": "Import Unreal Skeleton Mesh (.psk)/Animation Set (.psa) (280)",
"author": "Darknet, flufy3d, camg188, befzz",
"version": (2, 7, 7),
"blender": (2, 80, 0),

Both branches show Blender version 2.80.0.
Are these branches backwards-compatible with earlier Blender versions?

Also, it appears the **releases** page is collecting dust. The latest release was from year 2014.
- https://github.com/Befzz/blender3d_import_psk_psa/releases

**Comment by Blenux** [comment]
Yes it's backward compatible with 2.79, and latest branch is the most up to date one.

**Comment by Gnates** [comment]
Thanks. 
Also, to eliminate any confusion in the readme, can you add the **minimum** Blender version needed to use the add-on?
There are some users who were introduced to the add-on when Blender **2.78c** was released.

**Comment by Blenux** [comment]
Beffz would have to do that one, but one shouldn't use much past 2.79, quick test is older version (2.70 for example) have issues with importing Skeletons etc (meshes are fine), so I'd say min version would be 2.79.

**Comment by Befzz** [comment]
> backwards-compatible  

not anymore.  

latest 280 👇 
master 280  

master 280 👇 
master 270  




>  minimum Blender version needed

i've just made a quick test in 2.76b (Nov 3 2015) : success 

> releases page is collecting dust.

brushed away 😄
