### ISSUE TITLE
Error when trying to addplugin to blender

### ISSUE THREAD

**Issue by shrpies** [Befzz/blender3d_import_psk_psa#24]
I keep getting an error whenever i try to import the plugin "io_import_scene_unreal_psa_psk" 
https://imgur.com/a/8BQSndQ

**Comment by ricmetal** [comment]
same here.

**Comment by Befzz** [comment]
should be OK now.

**Comment by jeunathe** [comment]
Heya,
I still have the same problem even when using the updated file.

I'll ding into the code but for now I got no clue of how this works ;)

**Comment by Blenux** [comment]
Having no issue here with the latest build from today.
