### ISSUE TITLE
Rotation Only Option

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#26]
Hey Beffz, is there any way to have a option like 3ds Max's ActorX Importer where you can load in animations with Rotation only (Force Mesh Translation), some animations require this, in Blender you have to delete the key-frames first and then clear locations on the animation (ALT-G) which can get tidest at times, where ActorX Importer you can just press a button.

3ds Max.
<a href="https://imgur.com/uO1yDJg"><img src="https://i.imgur.com/uO1yDJg.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/QVdms0Q"><img src="https://i.imgur.com/QVdms0Q.png" title="source: imgur.com" /></a>

Blender.
<a href="https://imgur.com/YpIUkd7"><img src="https://i.imgur.com/YpIUkd7.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/6ZQI06i"><img src="https://i.imgur.com/6ZQI06i.png" title="source: imgur.com" /></a>

Once again thanks if you can do, and no drama if it's hard to implement, trying to help make Blender's Befzz Importer featured complete has it's 3ds Max counterpart :D.

**Comment by Befzz** [comment]
i need an psk/psa for testing.

**Comment by Blenux** [comment]
Sure uploaded same model above.

https://mega.nz/#F!MYEHBSQA!hGPmPMjIyQ__EMfod_Uf5A

**Comment by Befzz** [comment]
280, "latest":  

https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

**Comment by Blenux** [comment]
Awesome thanks again man, appreciate it.

**Comment by CharlieTemplar** [comment]
rotation only is fine for the general model shape, but you lose rooting to the ground and some animations rely on location too.  Attached soccer animation example (doesn't need rotation only, but just as example)
[Meshes.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/2923093/Meshes.zip)
