### ISSUE TITLE
When activating: ModuleNotFoundError: no module named 'blender_2'

### ISSUE THREAD

**Issue by tgienger** [Befzz/blender3d_import_psk_psa#27]
![image](https://user-images.githubusercontent.com/4080971/53278691-93553880-36bf-11e9-94d0-900d115de979.png)
I installed fine, no issues there I just cannot activate it.

**Comment by tgienger** [comment]
This is using the latest 2.8 download.

**Comment by Befzz** [comment]
checked right now

![image](https://user-images.githubusercontent.com/1160036/53279042-6edc7900-371e-11e9-9917-55e2acbf1193.png)

**Comment by tgienger** [comment]
I guess the filename is important...

**Comment by tgienger** [comment]
I guess the filename is important... 💯
