### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_4x4'

### ISSUE THREAD

**Issue by kiebo009** [Befzz/blender3d_import_psk_psa#29]
I have managed to install the plugin (270) in Blender (2.79) without any problems. But when I try to import any PSK files, I get the following error:

File "C\Users\MyName\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_270.py", line 1639 in execute
  error_callback=util_ui_show_msg
File "C\Users\MyName\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_270.py", line 678, in pskimport
  psk_bone.mat_world=parent.mat_world_rot.to_4x4()
AttributeError: 'NoneType' object has no attribute 'to_4x4'

location: <unknown location>:-1

I saw a few (solved) issues with similar errors, but I cannot seem to fix it. I am using the files from the 'latest' branch and using the correct version (270 for Blender 2.79). I installed Blender 2.8 as well and tried it with the 280 version, but I got the exact same error. The problem also shouldn't be with the PSK files I'm trying to import, since they work fine when I open them in 3ds Max.

**Comment by Befzz** [comment]
please, share your .psk files

**Comment by kiebo009** [comment]
[DAI_PSK_test.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/2923641/DAI_PSK_test.zip)

I hope this works, I extracted these PSK files from the game Dragon Age Inquisition using the ModMaker tool. Thank you very much for taking a look at them.

**Comment by Befzz** [comment]
thanks!  

added 2 lines of code.

fixed in the **latest** branch:

https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

**Comment by kiebo009** [comment]
Problem solved! 
Thank you very much for your help!
