### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by ArchUser87** [Befzz/blender3d_import_psk_psa#3]
Hey mate I've see you have updated the add-on again, thanks again for awesome work updating this regularly. I see you have tested it and it works on the assets your working on, I have tried it with the PUBG animations, however I get this......

![blender_psa](https://user-images.githubusercontent.com/25260650/28811124-97734b7e-76d0-11e7-85de-9ad9f7b3a171.PNG)

Do you still need to fix it or is it something I'm doing wrong on my end?, I've extracted these with Gildor's UModel with Character and Animations loaded then extracting the animations one by one.

**Comment by Befzz** [comment]
you are using updated version from **no_anim** branch.
So: **no animation**.

i've made few attempts to make it works, but no luck. (Stuck at 3D math). I will try again. later. 😄

**Comment by ArchUser87** [comment]
oh right silly me haha, all good keep up the good work....
