### ISSUE TITLE
Imported mesh deformed

### ISSUE THREAD

**Issue by 09williamsad** [Befzz/blender3d_import_psk_psa#30]
Hello

I have extracted the models from the game Battlefleet Gothic 2 Armada using umodel but on import some of them are deformed.

I am positive that this is not an issue with the model as the model viewer in umodel and 3ds max 2009 with plugin can view it without deformation
Blender 2.79 and 3ds max 2009
![untitled](https://user-images.githubusercontent.com/23011550/53823473-c2926200-3f69-11e9-9a5d-cb36283daa84.png)

I tried both 2.79 and 2.8 plugin versions along with renaming the pskx to psk to no effect.

Link to pskx file https://mega.nz/#!OHRwySxC!mvMsFI3oit4sz-6cPkxUJhpJ_2fluY00NQ2LGaWq4Do

**Comment by Befzz** [comment]
fixed in the **latest** branch:

https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

Detection of .pskx was not the same as ActorXImporter.

**Comment by 09williamsad** [comment]
Resolved
