### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by 09williamsad** [Befzz/blender3d_import_psk_psa#31]
Error on importing a PSK from the game Battle fleet gothic 2 Armada.
Works in the 3ds max plugin so I do not think it is an issue with the model.

Model https://mega.nz/#!CXBmhC7D!v-xomOfJpoFTEd7yTsP2F5s31ybMVIBM6zvE-VoZaoY

Error:
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_270.py", line 1656, in execute
    error_callback = util_ui_show_msg
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_270.py", line 723, in pskimport
    edit_bone.parent = armature_obj.data.edit_bones[psk_bone.parent.name]
KeyError: 'bpy_prop_collection[key]: key "TY_FrigateKraken_C005_All_Hide_ProwFeeders_Tentacles_R_Ctrl_0_01" not found'

**Comment by Befzz** [comment]
bone name:  
**.psk** vs. **blender** (after creation)
`TY_FrigateKraken_C005_All_Hide_ProwFeeders_Tentacles_R_Ctrl_0_01`
`TY_FrigateKraken_C005_All_Hide_ProwFeeders_Tentacles_R_Ctrl_0_0`

so. blender have a limitation...

**Comment by Befzz** [comment]
**psk** import:  
should work

**psa** import:  
will **not**  

in(at?) the *latest* branch, 270 version only

https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons
