### ISSUE TITLE
Rotated Skeletons

### ISSUE THREAD

**Issue by 09williamsad** [Befzz/blender3d_import_psk_psa#33]
Versio:n 2.0, latest as of 6/5/2019 11:30 GMT 1
Blender: 2.79b
Game: Hawken and others

Issue: Imported .psk files have the model and skeleton misaligned as per the below image, the left is blender and the right is Noesis, seems to be a blender issue as noesis works, weight painting is fine.
![Capture](https://user-images.githubusercontent.com/23011550/57220767-6f35a200-6ff4-11e9-9b3a-d1dd1b9672ad.JPG)
This also happened with other games like Project Nimbus and Mordhau but I dismissed it as an error with extraction as some models were fine.

Samples https://mega.nz/#!HOIgBKyQ!gy9ITIPc2g6Itz6cJJ7fDVr-CS4MFyquTwK7w5sYY2M

**Comment by Befzz** [comment]
![image](https://user-images.githubusercontent.com/1160036/57892764-dd763200-7848-11e9-9dc5-19d0b7888fe2.png)

Sometimes you need `Don't invert root bone` checked

**Comment by 09williamsad** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1160036/57892764-dd763200-7848-11e9-9dc5-19d0b7888fe2.png)
> 
> Sometimes you need `Don't invert root bone` checked

Is it possible for this to be detected and done automatically like with the noesis plugin?
I do alot of batch converting, would use noesis for this but it automatically flips UVs and batch flipping them back destroys the material name.

**Comment by Befzz** [comment]
I've checked the source code of noesis plugin.  
It looks like plugin simply always do "do not invert root bone".  

So.  
If you leave it always enabled it should be OK.

 = ^^ =

**Comment by 09williamsad** [comment]
Ok, will do.
I suggest if you update the plugin you set it to on by default as noesis converted psks in the past have not had this issue.
