### ISSUE TITLE
Dont find the UI of the addon?

### ISSUE THREAD

**Issue by roboserg** [Befzz/blender3d_import_psk_psa#34]
Sorry, I am must be blind, but I dont find the UI for the addon, where is it?
https://puu.sh/Dtgji/fa495e1e48.png

I installed and activated the addon - https://puu.sh/Dtgka/f52da77a2a.png

**Comment by Befzz** [comment]
https://github.com/Befzz/blender3d_import_psk_psa

![image](https://user-images.githubusercontent.com/1160036/57892072-57f18280-7846-11e9-8300-2e184014c804.png)

**Comment by roboserg** [comment]
Yes, I saw the guide. I dont have that "view" tab and consequently no PSK tab.

**Comment by Befzz** [comment]
![image](https://user-images.githubusercontent.com/1160036/57892252-ee25a880-7846-11e9-8127-e8bcbeac8fb8.png)

or press N

N and T are usefull keys :)

**Comment by roboserg** [comment]
Wow, thank you very much!
