### ISSUE TITLE
Scale Option?

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#38]
Hi Befzz, is it possible to get a scale option, currently when importing some assets with Blenders default unit scaling, the asset size is 100 times that of what they should be (comparing to UE4 Mannequin size), currently only way to adjust is to scale the asset to 0.010 and clear the scaling to apply it (Armature and Mesh), or the other alternative is to set Blender's Unit scale to 0.010, which isn't ideal when it comes to using Blenders physics or simulations, has it makes them not work properly.

If you can manage to do this, I and others would highly appreciate it (wish I knew how to!)

Thanks, Blenux.

![Annotation 2019-09-17 194524](https://user-images.githubusercontent.com/25260650/65031394-8910c980-d984-11e9-9004-1485e38b85ff.png)

**Comment by Befzz** [comment]
monkaHmm
Hi :)
Please share some .psk files.

What is considered an ideal mesh size range?
Up to 1? 10? 100?

**Comment by Blenux** [comment]
Probably 1, so a PSK import of Scale 1 equals to Blenders Unit Scale of 1, same has the gltf/fbx scaling of 1.

Here is everything from a .Blend file, PSK, GLTF (Blenders default), FBX.

https://mega.nz/#F!tJsmmaqQ!mAJh37g3uJqZ_wvJAjINwQ

**Comment by Blenux** [comment]
Works perfectly!, alot of people are going to like this, thanks!!!

**Comment by CraiigFX** [comment]
Thank you Befzz. You legend
