### ISSUE TITLE
Vertex Colors

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#39]
Hey Befzz, Gildor has added in Vertex Color support for his PSK ActorX Importer, any chance for this to be added into yours? Cheers again.

![c05e81f647b52e96c17c9972de7e42d4](https://user-images.githubusercontent.com/25260650/66728147-ef5b1000-ee8e-11e9-9919-85e2b316ef56.gif)

**Comment by Befzz** [comment]
psk please 😄

**Comment by Blenux** [comment]
crap :D


[SK_M_MED_Carbide_Body_Export.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/3724524/SK_M_MED_Carbide_Body_Export.zip)

**Comment by Befzz** [comment]
![image](https://user-images.githubusercontent.com/1160036/66779194-3b7d7300-eed6-11e9-8734-22922ca25d55.png)

1 Color "as is"
2 Converted to sRGB
3 gLTF

**Comment by Blenux** [comment]
Works perfectly, thanks again!
