### ISSUE TITLE
Error when trying to install add-on

### ISSUE THREAD

**Issue by jacquis-b** [Befzz/blender3d_import_psk_psa#40]
Hello,
I'm trying to install this add-on to Blender but an error message appears when I try to enable it. Is there an easy way I can fix it? Thanks.
![Untitled](https://user-images.githubusercontent.com/57181721/67860007-d13f1200-fb14-11e9-82fe-852df90a0473.png)

**Comment by Blenux** [comment]
There is 2 branches, one master which is 8 months old and latest which is only couple weeks old, you'll want to use the newest one.

https://raw.githubusercontent.com/Befzz/blender3d_import_psk_psa/latest/addons/io_import_scene_unreal_psa_psk_280.py
