### ISSUE TITLE
Problems importing animation

### ISSUE THREAD

**Issue by cbaal83** [Befzz/blender3d_import_psk_psa#41]
Hi Guys,

iam trying to import an quite old unreal version (lineage 2, unreal 2).
The model import work's just fine, but when i try to import an animation, i get the following issue:

 
Traceback (most recent call last):
[issue.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/3985027/issue.zip)

```
  File "C:\Users\chris\Downloads\blender-2.81a-windows64\2.81\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1802, in execute
    error_callback = util_ui_show_msg
  File "C:\Users\chris\Downloads\blender-2.81a-windows64\2.81\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1367, in psaimport
    psa_bone.fcurve_quat_w = action.fcurves.new(data_path, index = 0)
RuntimeError: Error: F-Curve 'pose.bones["Bip01 L Finger01"].rotation_quaternion[0]' already exists in action 'spwait01'
```

I've attached the model and the animation. Hope you can help me in any way :).

Thank's a lot for your hard work!
//Chris

**Comment by Befzz** [comment]
This PSK have `Bip01 L Finger01` on both hands.  
Blender doesn't allow duplicates.... 

Updated **latest** branch: 
https://raw.githubusercontent.com/Befzz/blender3d_import_psk_psa/latest/addons/io_import_scene_unreal_psa_psk_280.py

**Comment by cbaal83** [comment]
That was really quick.

Works perfectly fine! Thank you :)

//Chris
