### ISSUE TITLE
Workplace Filters

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#42]
Hi I just notice with the addon, if one wants to filter their add-on's list, enabling it disables access to this add-on completely, might be something to look into if possible.

![Annotation 2019-12-27 192440](https://user-images.githubusercontent.com/25260650/71509205-aee02f80-28de-11ea-8cb3-e14ac335e2aa.png)
![Annotation 2019-12-27 192510](https://user-images.githubusercontent.com/25260650/71509207-b1db2000-28de-11ea-80b5-5cf6f7f4df02.png)

**Comment by Befzz** [comment]
as of 2.93  
![image](https://user-images.githubusercontent.com/1160036/143907715-56e02e1b-7d53-4a6b-9d88-99037b89e7d4.png)
  
i did nothing 😄
