### ISSUE TITLE
Kurtzpel extra UV channels don't import properly

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [Befzz/blender3d_import_psk_psa#44]
Not sure how to describe it s here's a umodel picture of the UV.
![image](https://user-images.githubusercontent.com/33284629/73199452-c81e0b00-412c-11ea-9eaa-9f8d9c6b9aa7.png)
![image](https://user-images.githubusercontent.com/33284629/73199467-ce13ec00-412c-11ea-83ba-c4cfd0df1ff2.png)
The gltf importer imports the UV's just fine as does Gildors 3DS Max importer so it's definitely an issue with this importer.
[sample.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/4118537/sample.zip)
In this ZIP is the gltf and a psk.

**Comment by Blenux** [comment]
Posted on gildor forum that the importer works fine....

![Annotation 2020-01-28 105753](https://user-images.githubusercontent.com/25260650/73224312-3a3e3080-41bd-11ea-9e21-03af1f5c350c.png)

**Comment by CosmicDreamsOfCode** [comment]
Make sure you look at the other UV channels.
Those are the ones that are broken.

**Comment by Blenux** [comment]
ah yeah I see, website didn't refresh correctly :D

**Comment by Befzz** [comment]
yes, extrauvs is broken. i'll check it

**Comment by Befzz** [comment]
Thanks for reporting this issue ^_^  

Made UV maps equal to gltf's importer  (atleast for this psk file 😄  )

https://raw.githubusercontent.com/Befzz/blender3d_import_psk_psa/latest/addons/io_import_scene_unreal_psa_psk_280.py

**Comment by CosmicDreamsOfCode** [comment]
Works like a charm. Thanks!
