### ISSUE TITLE
Error Importing Mirror's Edge assets (Could be multiple UV)

### ISSUE THREAD

**Issue by Sandshee** [Befzz/blender3d_import_psk_psa#48]
```
File "C:\...\_280.py", line 1759, in execute error_callback = util_ui_show_msg
File "C:\...\_280.py", line 968, in pskimport uvLayer.data[uv_index].uv = (uv_coords[0], 1.0 = uv_coords[1])
IndexError: bpy_prop_collection[index]: index 3030 out of range, size 3030

location <unknown location> :-1
```

I know the Mirror's Edge assets have 2 UV maps, and previous importers didn't like this, it could be an error from this still.

Should be recreatable with the following asset:

[Skyscraper.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/4658994/Skyscraper.zip)

**Comment by Befzz** [comment]
it works in plugin version 2.7.13 (_branch_ **latest**)



![image](https://user-images.githubusercontent.com/1160036/82508841-f1650b80-9b0e-11ea-843c-3e63c72cda7e.png)

https://raw.githubusercontent.com/Befzz/blender3d_import_psk_psa/latest/addons/io_import_scene_unreal_psa_psk_280.py  


![image](https://user-images.githubusercontent.com/1160036/82509185-cb8c3680-9b0f-11ea-8682-1a1e25cd6357.png)

![image](https://user-images.githubusercontent.com/1160036/82508935-3c7f1e80-9b0f-11ea-8efe-347a170492e5.png)
