### ISSUE TITLE
cant import psa

### ISSUE THREAD

**Issue by geekn00b** [Befzz/blender3d_import_psk_psa#50]
when I import psa in the latest version the character gets buged

**Comment by Blenux** [comment]
Screenshots would help, and not every animation is supported with uModel.

**Comment by geekn00b** [comment]
the ones that work don't work anymore, 
https://user-images.githubusercontent.com/45574749/84782096-03c34f80-afbe-11ea-8183-4b074f0cff97.png       fire elf pose was working in older versions

**Comment by Blenux** [comment]
Still is ?

![Annotation 2020-06-17 013307](https://user-images.githubusercontent.com/25260650/84795307-a6211880-b03a-11ea-9c8c-3a0b12a238e1.png)

**Comment by geekn00b** [comment]
I really dont know whats happend but only happends in the latest version

**Comment by geekn00b** [comment]
now I know what was hapening skins I import with older version of the addon only qorks with the old version
