### ISSUE TITLE
Update timeline range

### ISSUE THREAD

**Issue by T-Jeremy** [Befzz/blender3d_import_psk_psa#55]
Hello, thanks for this plugin, it is very useful.

I have a problem while importing multiple animations at once.
I'm using version 280 on latest branch (2.7.14).

I don't have the "All actions to NLA track" because the README says that it is broken.

I checked the "update timeline range" to get the correct duration timeline for each imported animations.

However, it looks like the timeline is set to the first chosen animation while importing.

Example : 

First animation timeline : 
![image](https://user-images.githubusercontent.com/14940407/95835665-cdfd6000-0d3e-11eb-8a9c-7e0c782626ca.png)

Second animation timeline : 
![image](https://user-images.githubusercontent.com/14940407/95835726-e1a8c680-0d3e-11eb-8b4d-7f0e621af5cb.png)

Third animation timeline : 
![image](https://user-images.githubusercontent.com/14940407/95835754-eb322e80-0d3e-11eb-96d5-18e510a1432e.png)

What i would like to do is importing a bunch of animation in one time, and getting correct timeline range for each animations.

Thank you.

**Comment by Befzz** [comment]
hi :) 
"All actions to NLA track" is works fine in 2.8 (i will update the README )  

AFAIK timeline range can be set only per scene.  
One scene - one timeline range - but many actions.  

So, simply: you can't have timeline range for each action.  

Timeline range is set to longest imported action.  ( If  "All actions to NLA track" disabled )

**Comment by Befzz** [comment]
closing old issues.
