### ISSUE TITLE
Cant even Import the add on

### ISSUE THREAD

**Issue by NiteSwapper** [Befzz/blender3d_import_psk_psa#62]
![image](https://user-images.githubusercontent.com/68803706/112717938-b13e9880-8f2a-11eb-84e2-79ecb67ae009.png)

**Comment by Befzz** [comment]
straaange error.  

Does addon installed via "Install.." button?  

Script should exist there: *%APPDATA%\Blender Foundation\Blender\2.92\scripts\addons*   

![image](https://user-images.githubusercontent.com/1160036/112729713-9f66f080-8f3e-11eb-9409-ff317bb81a93.png)

**Comment by HuskySquirrel** [comment]
I see the same error on trying to import 280, I do not see this error with 270.
The script does exist in the addons folder you mention.
![image](https://user-images.githubusercontent.com/8215804/112752752-6a08e400-8fcc-11eb-8e60-74119da40710.png)

**Comment by Befzz** [comment]
@HuskySquirrel   
**_280.py** can be used only in 2.80+ Blender.  
Your version is 2.79 😄

**Comment by HuskySquirrel** [comment]
> @HuskySquirrel
> **_280.py** can be used only in 2.80+ Blender.
> Your version is 2.79 😄

Oh god oops, so sorry!
