### ISSUE TITLE
Fortnite emotes

### ISSUE THREAD

**Issue by Vortex-0202** [Befzz/blender3d_import_psk_psa#63]
Gostaria de saber onde acho os emotes só tenho o emote do personagem segurando a arma queria uma que ele estivesse segurando a picareta

**Comment by Befzz** [comment]
i can't help you with this problem. Here we are solving issues about importing ".psk/.psa" files.  
eu não posso te ajudar com este problema. Aqui, estamos resolvendo problemas sobre a importação de arquivos ".psk / .psa".
