### ISSUE TITLE
DONLOAD

### ISSUE THREAD

**Issue by REDninjaGAMING** [Befzz/blender3d_import_psk_psa#65]
HOW THE FUCK DO I DONLOWD THIS BULL SHIT

**Comment by Befzz** [comment]
![image](https://user-images.githubusercontent.com/1160036/120226405-cfd54e80-c24f-11eb-8a84-fe24530d1d4a.png)

**Comment by Blenux** [comment]
You simply right click the link on the main page and save as.....
