### ISSUE TITLE
Head Location Error

### ISSUE THREAD

**Issue by LievreAI** [Befzz/blender3d_import_psk_psa#66]
![3](https://user-images.githubusercontent.com/84988313/122172084-17332000-ce89-11eb-9b3d-3b27816a08ea.png)
![4](https://user-images.githubusercontent.com/84988313/122172089-18644d00-ce89-11eb-8bff-9b927de780d8.png)

hey guys i have some error using the script the head hair location are no in the right position i dont know if that is a skeleton problem but i attach the model so you can check it 
[ModelData.zip](https://github.com/Befzz/blender3d_import_psk_psa/files/6660858/ModelData.zip)

**Comment by Befzz** [comment]
![image](https://user-images.githubusercontent.com/1160036/126052690-e814ecc5-0e70-4499-96cc-e5c7f2c66940.png)
![image](https://user-images.githubusercontent.com/1160036/126052676-84642521-4517-4470-a836-ab9fe1d36a6e.png)

assembling the model is your responsibility :)  

To face and hair set Rotation X -90
Add object constraint "Child of" ... BODY ao ...   Bone: b_C_Head
It looks ok.

plugin simply do not know anything about it
