### ISSUE TITLE
Syntax Error on Install

### ISSUE THREAD

**Issue by bjaurelio** [Befzz/blender3d_import_psk_psa#71]
I am trying to enable the plugin, but I get the following error when I try to enable the add-on.
![image](https://user-images.githubusercontent.com/91978516/136072016-5535a276-ab8f-4b96-bc54-fb4eb66027a8.png)

**Comment by Blenux** [comment]
You save the .py file has a html file.

[https://raw.githubusercontent.com/Befzz/blender3d_import_psk_psa/latest/addons/io_import_scene_unreal_psa_psk_280.py](url)

click on the link above and CTRL+S to save has a .py file.
