### ISSUE TITLE
Blender not finding the .py file

### ISSUE THREAD

**Issue by jawlessbug0758** [Befzz/blender3d_import_psk_psa#80]
After saving the .py file from the link, windows saves it as a .txt file instead, so Blender can't use it. even when saving as .py, windows sees it as ".py.txt" instead

**Comment by Blenux** [comment]
Try right click on it and Save Link As?

Also you can simply rename it and remove the .txt, then refresh the addon list.

**Comment by jawlessbug0758** [comment]
I swear I tried all those things lol. 
![Screenshot (7)](https://user-images.githubusercontent.com/42917343/154836037-06a15063-e95d-4c07-87da-4061ff04c5fb.png)
![Screenshot (8)](https://user-images.githubusercontent.com/42917343/154836038-2c628704-0d5f-4712-8e53-a49e67cca1a4.png)
![Screenshot (9)](https://user-images.githubusercontent.com/42917343/154836041-259957d5-376c-406a-b57e-d5c843860bb9.png)

**Comment by Blenux** [comment]
oh I see the issue, the addon file manager there is looking for a .zip file, you will need to manually place the .py into the addons folder, or simply right click the .py file and send to compressed file to make it a .zip, then refresh the page and should come up.

**Comment by jawlessbug0758** [comment]
I was having this issue on 3.0, so I initially assumed that was the issue. Since that's not the case I'll try again in 3.0

**Comment by Blenux** [comment]
I see, even works on 3.2 Alpha, unless something major changes, should work for awhile.

**Comment by jawlessbug0758** [comment]
Okay so after sending it to a .zip Blender found it, but after installing, .psk files still aren't on the list in the import menu

**Comment by Blenux** [comment]
You will have to check the checkbox in the addon preference tab to enable it...

![Screenshot 2022-02-20 203151](https://user-images.githubusercontent.com/25260650/154836550-6c53facb-90fc-4828-ad91-9110995629f1.png)

**Comment by jawlessbug0758** [comment]
Where would I find that check box?

**Comment by Blenux** [comment]
Edit - Preferences - Addons Tab - search for PSK
![Screenshot 2022-02-20 203907](https://user-images.githubusercontent.com/25260650/154836796-af1142cb-2d4e-45b8-b69e-b3473e12a89b.png)

**Comment by jawlessbug0758** [comment]
That's what I thought, but it's not there. Whenever I check the properties of that .py file, it's still showing it as .txt despite having renamed it when saving.

**Comment by jawlessbug0758** [comment]
Nvm Got it. opened it up in notepad, saved it again and renamed so it wouldn't save as a .txt again. Thank for all the help.

**Comment by Blenux** [comment]
Oh ok good, be sure to close this so everyone knows its solved.
